### PR TITLE
Move all Twisted support code to twistedsupport package

### PR DESCRIPTION
**Pull request by jml**
Intent is purely to move code around without causing behavior change, so that all the Twisted stuff is in one spot.

* Move all Twisted support code to private modules in `testtools.twistedsupport` package
* Export all public code from `testtools.twistedsupport` package
* Continue to export public code from old locations (e.g. so `testtools.deferredruntest.AsynchronousDeferredRunTest` still works)
* Move all tests for Twisted support code to `testtools.tests.twistedsupport`, to parallel matchers
* Move `NeedsTwistedTestCase` to its own helper module, rather than importing from `test_spinner` as before

[Review on Reviewable](https://reviewable.io/reviews/testing-cabal/testtools/202)

### CODE REVIEW

**Comment by jml** [comment]
Rebased on recent changes to master. No behavioural changes. Will merge in 24 hours unless I hear anything.

**Comment by rbtcollins** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[testtools/deferredruntest.py, line 1 \[r1\]](https://reviewable.io:443/reviews/testing-cabal/testtools/202#-K9iDLeb2gONUPzjLGKw:-K9iDLeb2gONUPzjLGKx:-341699145) ([raw file](https://github.com/testing-cabal/testtools/blob/9b0ed727e5da1b36078630c397a83bedb0c3c6a7/testtools/deferredruntest.py#L1)):*
It's my understanding the Copyright statements require years to be valid.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/testing-cabal/testtools/202)*

**Comment by rbtcollins** [comment]
Assuming its all just a move, then it seems fine to me, modulo the copyright statement thing.

**Comment by jml** [comment]
Thanks. Copyright years restored & bumped (I don't know if it's required or not, but IP minutiae is even more tedious than resolving needless diff conflicts).

Merged as e571d9c.

**Comment by jml** [comment]
Reverted as 092d434. The Travis CI build is failing and I shouldn't have merged it in the first place.

**Pull request closed without merging**
