### PR TITLE
Migrate to pyproject.toml

### PR DESCRIPTION
**Pull request by jelmer**
Migrate to pyproject.toml

### CODE REVIEW

**Comment by jelmer** [comment]
Alas, it looks like pbr doesn't support project config in pyproject.toml yet :-/

**Comment by bigjools** [comment]
FWIW I switched a few of my projects to `pyproject.toml` and removed `pbr` in the process. I changed my build system to `hatch` and added this config

```
[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "_version.py"
```

You still get the auto-versioning based on Git tag. You can also use 
`[tool.hatch.build.targets.wheel.shared-data]`
to add extra data files in the wheel.

I think `pbr` has run its course and should go now.

**Comment by jelmer** [comment]
Hmm, hatch looks interesting - and I think I've come across it in other projects.

Doesn't appear to be packaged in Debian yet, so perhaps I'll have a look at that first.

**Comment by bigjools** [comment]
Here's one of mine if you want to see what we're doing with it. https://github.com/juledwar/soufi/
I'm not using the test matrix it can do (still using GH actions for that) but it's SO useful being able to do things like `hatch run tests` or `hatch run python3`

**Pull request closed without merging**
