### PR TITLE
Reduce dependencies

### PR DESCRIPTION
**Pull request by stephenfin**
I want to get to a point where fixtures and testtools don't form a circular
dependency chain. Before we can get there though, there's a lot more things
that appear to need cleaning up, namely our dependency on testtools2, extras,
and mimeparse, all of which are effectively EOL.

### CODE REVIEW

**Comment by stephenfin** [comment]
This is passing locally, so I've no idea what's up here :disappointed:

**Comment by mtreinish** [comment]
@stephenfin I just merged #277 which removed the unittest2 dependency could you rebase this to do the other requirement cleanup (extras and mimeparse)? Once it's rebased if it's still failing i'll take a look and see if I can reproduce the failures locally.

**Comment by stephenfin** [comment]
> @stephenfin I just merged #277 which removed the unittest2 dependency could you rebase this to do the other requirement cleanup (extras and mimeparse)? Once it's rebased if it's still failing i'll take a look and see if I can reproduce the failures locally.

Done. Turns out the failure was because I was removing `extras` but `fixtures` has an indirect dependency on this via `testtools`. I've pushed https://github.com/testing-cabal/fixtures/pull/46 to drop support for that. If you could take a look at this also, I'd be very appreciative. Eventually I'd like to uncouple `testtools` and `fixtures`, such that the former depends on the latter but not the other way around, but there's a bit of work to go for that yet.

**Comment by stephenfin** [comment]
Hurrah. Can we get a new release of this and fixtures so I can proceed with dropping additional dependencies?

**Pull request merged**
