### PR TITLE
Add map_bytes for Content

### PR DESCRIPTION
**Pull request by jml**
Makes `Content` a functor, which can be handy for some operations.

[Review on Reviewable](https://reviewable.io/reviews/testing-cabal/testtools/179)

### CODE REVIEW

**Comment by jml** [comment]
I want a sanity check before adding a new API, so not merging yet.

**Comment by rbtcollins** [comment]
This is an ok thing to do.

Alternative option. If we made Content have an __iter__ (that yields bytes), this could be spelt by users as:
c = Content(base.content_type, lambda: map(base, transform))

hmmm, well it can be spelt that way by users already I guess.

I wonder if we're going to dig ourselves a naming consistency hole here though - since this is the first of this sort of thing we've got. 

That said, this isn't currently exported (in __all__ in the root and down to the place its defined), so I'd rather it either be exported, or be _ prefixed, to make its status crystal clear.

**Comment by jml** [comment]
Exported from testtools.content (we don't presently export anything from testtools.content further out—I believe our historical thinking was that it might want to become its own package).

Separately from this PR, we should document the conventions around exactly what is & isn't public and thus supported.

**Comment by jml** [comment]
@rbtcollins What's the resolution on this PR? Go or no-go?

**Comment by jml** [comment]
Don't want this on my Github dashboard. Others are free to re-submit if they'd like.

**Comment by rbtcollins** [comment]
Ugh, sorry.

**Pull request closed without merging**
