### PR TITLE
Format code with ruff

### PR DESCRIPTION
**Pull request by jelmer**

### CODE REVIEW

**Comment by bigjools** [comment]
It's a bit tragic that `ruff` doesn't have `black`'s setting `skip-string-normalization`.

**Comment by jelmer** [comment]
I'm actually quite a fan of string normalization, but could be possibly be persuaded to port skip-string-normalization to ruff.

**Comment by bigjools** [comment]
Yeah I don't mind it too — except when you completely destroy the current `git blame` on a mature code base.

**Comment by jelmer** [comment]
I'll merge sometime in 2024 if there are no objections.

**Comment by stephenfin** [comment]
> Yeah I don't mind it too — except when you completely destroy the current `git blame` on a mature code base.

Just create a `.git-blame-ignore-revs` file. GitHub respects that by default and you can configure your local Git to do the same. I stick this header into the file each time I create one:

```
# You can configure git to automatically use this file with the following config:
# git config --global blame.ignoreRevsFile .git-blame-ignore-revs
```

**Comment by bigjools** [comment]
> Just create a `.git-blame-ignore-revs` file. [GitHub respects that](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view) and you can configure your local Git to do the same. I stick this header into the file each time I create one:
> ```
> # You can configure git to automatically use this file with the following config:
> # git config --global blame.ignoreRevsFile .git-blame-ignore-revs
> ```

TIL!

**Review by bigjools — APPROVED** [review]

**Pull request merged**
