### PR TITLE
Drop support for EOL 3.5

### PR DESCRIPTION
**Pull request by hugovk**
Also:

* Upgrade Python syntax with https://github.com/asottile/pyupgrade `--py36-plus`
* Update and simplify GHA test workflow

### CODE REVIEW

**Review by mtreinish — COMMENTED** [review]
Code-wise this LGTM, but can you split this into 2 PRs, one adding 3.9 support to the package metadata (and probably most of the gha config cleanup) and the other dropping 3.5 support. I think for the next release (which should be relatively soon) we should still include 3.5 support and say in the release notes for it that 2.5.0 is the last release with 3.5 support. We haven't previously advertised dropping 3.5 before so I don't want to catch any potential 3.5 users by surprise.

**Comment by hugovk** [comment]
Yep, that sounds reasonable, please see https://github.com/testing-cabal/testtools/pull/310 for adding 3.9.

After that's merged (to avoid conflicts), I'll rebase and update this one. Thanks!

**Comment by hugovk** [comment]
I've created https://github.com/testing-cabal/testtools/pull/313 to note 2.5.0 is the last release with Python 3.5 support.

PR #310 is merged and I've rebased this. The NEWS in this PR can be updated once 2.5.0 is out.

**Comment by hugovk** [comment]
Two CI failures:

# 3.10-dev

I get the same on `master`:

https://github.com/hugovk/testtools/runs/3170432249?check_suite_focus=true
https://github.com/testing-cabal/testtools/pull/309/checks?check_run_id=3170451427

# pypy3

I don't get this on my PR build:

https://github.com/hugovk/testtools/runs/3170451055?check_suite_focus=true
https://github.com/testing-cabal/testtools/pull/309/checks?check_run_id=3170451480

**Comment by hugovk** [comment]
Merge conflict resolved!

Is there anything more needed here? Thanks!

**Comment by stephenfin** [comment]
@hugovk Can you rebase this so we can pick up new test runs?

**Comment by hugovk** [comment]
Rebased!

This needs the 3.5 status check being marked as NOT required.

At the same time, the new 3.10 one can be marked as required.

image

**Review by stephenfin — APPROVED** [review]

**Review by jelmer — APPROVED** [review]

**Comment by hugovk** [comment]
Updated to add a final, noop job to indicate success:

image

Its success depends on the build step fully passing. So instead of needing to https://github.com/testing-cabal/testtools/pull/309#issuecomment-1031459025 each and every time a Python version is added to or removed from the matrix, we can just add this new "test successful" as the required check.

**Comment by hugovk** [comment]
Closing this year-old PR to clear my list, happy to re-open if you want to merge :)

**Comment by jelmer** [comment]
Sorry about that. If you reopen, I promise I'll take a look at merging it.

**Comment by hugovk** [comment]
No problem, re-opened!

**Review by jelmer — APPROVED** [review]

**Comment by jelmer** [comment]
Finally figured out how to mark the 3.5 tests as no longer required :)

**Comment by stephenfin** [comment]
We probably want to do 3.6 next. I think that's EOL now too

**Comment by hugovk** [comment]
Yes, 3.6 was EOL in December 2021 (3.7 will be June 2023). 


https://endoflife.date/python

**Pull request merged**
