### PR TITLE
Add Manuel testing

### PR DESCRIPTION
**Pull request by OddBloke**
This adds 54 tests based on the documentation for test authors. These tests have been written by taking each of the existing code snippets and wrapping them in a TestCase.

We then collate these in to a test suite at the bottom of the document and run it, as Manuel (unsurprisingly) doesn't support embedding TestCases within documentation.

This addresses https://bugs.launchpad.net/testtools/+bug/1183332 (at least partially).

[Review on Reviewable](https://reviewable.io/reviews/testing-cabal/testtools/74)

### CODE REVIEW

**Comment by rbtcollins** [comment]
Ping @OddBloke

**Comment by rbtcollins** [comment]
@jml reckon you'd want to pick this up, or perhaps @thomir ?

**Comment by jml** [comment]
Not particularly. I want to move most of the detailed prose docs to API
docs and then include them ala twisted-support.rst, but for automated
testing would start afresh

**Comment by thomir** [comment]
I'd be willing, but it's unlikely I'll have the time in the next few weeks
- but you never know...

I've not used manuel before, but it seems awfully close to doctests, which
makes me nervous...

On 16 February 2016 at 11:35, rbtcollins <notifications@github.com> wrote:

> @jml <https://github.com/jml> reckon you'd want to pick this up, or
> perhaps @thomir <https://github.com/thomir> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/testing-cabal/testtools/pull/74#issuecomment-184425800>
> .
>



-- 
Thomi Richards

**Comment by rbtcollins** [comment]
Ok, lets close then.

**Pull request closed without merging**
